spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Mohak-Mishra/SpringCloudConfigServerEX.git
          username: mohakmishra2207@gmail.com
          password: cycgi1-tyship-Zoxjeg
          default-label: main
  application:
   name: SpringCloudConfigServer
server:
  port: 8888